version: "3"

services:
  api:
    image: "node:16-alpine"
    env_file: '.env.docker'
    container_name: "api"
    volumes:
      - "./:/source"
    working_dir: /source
    ports:
      - "8000:8000"
    command: sh -c "yarn && yarn start"
